add testing for minimal json configurations

diff --git a/test/config/dc_compute_test b/test/config/dc_compute_test
--- a/test/config/dc_compute_test
+++ b/test/config/dc_compute_test
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
-# Copyright (c) 2017, Cisco Systems
+# Copyright (c) 2018, Cisco Systems
 # All rights reserved.
-#
+
 # Redistribution and use in source and binary forms, with or without modification,
 # are permitted provided that the following conditions are met:
 #
@@ -26,17 +26,9 @@
 #
 
 set -xe
-export BUILD_NUMBER=$(cat ./version)
-./install_deps
-go generate -v ./cmd/...
-go install -v ./cmd/...
 
-set +x
-tools="arc amp audit spark"
-for tool in $tools; do
-  $tool version
-done
+export ARC_ROOT="$PWD/config"
 
-cd test
-./test_all
-cd - >/dev/null 2>&1
+# This is expected to fail.
+arc dc_compute info && exit 1 || exit 0
+
